#!/bin/bash

echo "=== VERIFICACIÓN RÁPIDA MERCADOPAGO ==="
echo ""
echo "✅ Tu aplicación está corriendo en: http://localhost:3000"
echo ""
echo "🔍 PASOS PARA DEBUGGEAR EL PROBLEMA:"
echo ""
echo "1️⃣  Abre tu navegador y ve a: http://localhost:3000"
echo ""
echo "2️⃣  Haz una compra de prueba (agrega productos al carrito)"
echo ""
echo "3️⃣  En el checkout, llena todos los datos y dale 'Pagar'"
echo ""
echo "4️⃣  Observa TU TERMINAL aquí - deberían aparecer logs como:"
echo "   '=== DEBUGGING MERCADOPAGO ==='"
echo "   'Datos recibidos: {...}'"  
echo "   'PREFERENCIA CREADA: {...}'"
echo ""
echo "5️⃣  Copia y pégame TODOS los logs que aparezcan"
echo ""
echo "🚨 IMPORTANTE:"
echo "   - Si NO ves estos logs = hay un problema antes de MercadoPago"
echo "   - Si SÍ ves los logs = el problema está en MercadoPago mismo"
echo ""
echo "📋 DATOS DE PRUEB SUGERIDOS:"
echo "   Nombre: Test User"
echo "   Email: test@test.com"
echo "   Teléfono: 3001234567"
echo "   Ciudad: Bogotá"
echo "   Dirección: Calle 123 #45-67"
echo ""
echo "🔗 Después de llenar el formulario, MercadoPago debería abrir en:"
echo "   una nueva pestaña mostrando los productos y el botón de pago"
echo ""
echo "=== ESPERANDO TUS LOGS... ===");